### ISSUE TITLE
Incorrect rendering of css calc() statements

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#64]
Both leading and trailing spaces are lost around a plus operator in a calc() statement if the sign of the stacks variable following it is negative. All other operators function as expected.

This occurs in both Stacks 2 and 3.

For example:

```
#%id%>.top-edge.con-arrow::after{
top: calc(%id=pos%%id=units% - %id=arrowAngleComp%%id=units%;
top: calc(%id=pos%%id=units% / %id=arrowAngleComp%%id=units%;
top: calc(%id=pos%%id=units% * %id=arrowAngleComp%%id=units%;
top: calc(%id=pos%%id=units% + %id=arrowAngleComp%%id=units%;
}
```

Renders to:

``` css
#stacks_in_211_page3>.top-edge.con-arrow::after {
    top: calc(4.97vw - -2.00vw);
    top: calc(4.97vw / -2.00vw);
    top: calc(4.97vw * -2.00vw);
    top: calc(4.97vw+-2.00vw);
}
```
